### ISSUE TITLE
How to access the bullmq job in the Job class handler

### ISSUE THREAD

**Issue by p3drosola** [RomainLanz/adonis-bull-queue#46]
In the v2 version of this library for adonis v5, to access the bullmq job you could access `this.job` in the handler function.

I've checked the source and can see the `#bullMqJob` private variable, but it's not accesible by the classes that inherit from Job.

Would you accept a pr for a `getJob` function, or a making the variable public?

**Comment by RomainLanz** [comment]
Hey @p3drosola! 👋🏻 

What's your use case for accessing the job instance?
I would rather create a proper getter for your use case than give direct access to the BullMQ Job instance. Why? Because I may want to create a proper abstraction in the future so we can have a "real" queue package, and being deeply linked to BullMQ will not help. 😄

**Comment by rutonyru** [comment]
Hi,
Ok. That's why I can not access to the job in my handle function. You're doing a pretty good job and of course, I understand the reason why. Even I can't wait for a "good solution", I can also describe my use case. 
My use case could be : 
My job can be a "waiting job" to access to an asynchronous data (slow integration of a file in a document manager). I decided to init the job with 5 attempts and a waiting delay of 5000ms :
  - So my handle function will have to manage the loss of the document (the document is deleted by the user before the end of the process) => "moveToFailed". 
  - The job found that the integration is still processing : => go on (not an error, not a success), next time job ? exit from the function ?
  - The handle found that the doc integration is finished with success => End of the job with sucess. moveToSuccess()
  - The handle found that the doc integration is finished with an error => moveToFailed
Thanks,
Antoine

**Comment by RomainLanz** [comment]
You are right. Better off leveraging BullMQ than trying to create a bad abstraction for now.

It will be available using `this.getJob()` inside the `handle` or `rescue` method.

**Comment by p3drosola** [comment]
Hi @RomainLanz , 

I'm taking another stab at upgrading my app. I saw you [added the getJob method ](https://github.com/RomainLanz/adonis-bull-queue/commit/97dac6ddf50731c6fa63523835c64153a641202a) but the latest version on NPM doesn't include it. Any chance you could publish a new version?

Thanks in advance!

**Comment by RomainLanz** [comment]
Done! 👍🏻
